  1 # Edit this configuration file to define what should be installed on                                                                                                                                                                      
  2 # your system.  Help is available in the configuration.nix(5) man page                                                                                                                                                                    
  3 # and in the NixOS manual (accessible by running ‘nixos-help’).                                                                                                                                                                           
  4                                                                                                                                                                                                                                           
  5 { config, pkgs, ... }:                                                                                                                                                                                                                    
  6                                                                                                                                                                                                                                           
  7 {                                                                                                                                                                                                                                         
  8   imports =                                                                                                                                                                                                                               
  9     [ # Include the results of the hardware scan.                                                                                                                                                                                         
 10       ./hardware-configuration.nix                                                                                                                                                                                                        
 11     ];                                                                                                                                                                                                                                    
 12                                                                                                                                                                                                                                           
 13   # Bootloader.                                                                                                                                                                                                                           
 14   boot.loader.systemd-boot.enable = true;                                                                                                                                                                                                 
 15   boot.loader.efi.canTouchEfiVariables = true;                                                                                                                                                                                            
 16                                                                                                                                                                                                                                           
 17   networking.hostName = "nixos"; # Define your hostname.                                                                                                                                                                                  
 18   # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.                                                                                                                                                    
 19                                                                                                                                                                                                                                           
 20   # Configure network proxy if necessary                                                                                                                                                                                                  
 21   # networking.proxy.default = "http://user:password@proxy:port/";                                                                                                                                                                        
 22   # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";                                                                                                                                                                     
 23                                                                                                                                                                                                                                           
 24   # Enable networking                                                                                                                                                                                                                     
 25   networking.networkmanager.enable = true;                                                                                                                                                                                                
 26                                                                                                                                                                                                                                           
 27   # Set your time zone.                                                                                                                                                                                                                   
 28   time.timeZone = "Atlantic/Azores";                                                                                                                                                                                                      
 29                                                                                                                                                                                                                                           
 30   # Select internationalisation properties.                                                                                                                                                                                               
 31   i18n.defaultLocale = "en_US.UTF-8";                                                                                                                                                                                                     
 32                                                                                                                                                                                                                                           
 33   i18n.extraLocaleSettings = {                                                                                                                                                                                                            
 34     LC_ADDRESS = "pt_PT.UTF-8";                                                                                                                                                                                                           
 35     LC_IDENTIFICATION = "pt_PT.UTF-8";                                                                                                                                                                                                    
 36     LC_MEASUREMENT = "pt_PT.UTF-8";                                                                                                                                                                                                       
 37     LC_MONETARY = "pt_PT.UTF-8";                                                                                                                                                                                                          
 38     LC_NAME = "pt_PT.UTF-8";                                                                                                                                                                                                              
 39     LC_NUMERIC = "pt_PT.UTF-8";                                                                                                                                                                                                           
 40     LC_PAPER = "pt_PT.UTF-8";                                                                                                                                                                                                             
 41     LC_TELEPHONE = "pt_PT.UTF-8";                                                                                                                                                                                                         
 42     LC_TIME = "pt_PT.UTF-8";                                                                                                                                                                                                              
 43   };                                                                                                                                                                                                                                      
 44                                                                                                                                                                                                                                           
 45   # Enable the X11 windowing system.                                                                                                                                                                                                      
 46   services.xserver.enable = true;                                                                                                                                                                                                         
 47                                                                                                                                                                                                                                           
 48   # Enable the GNOME Desktop Environment.                                                                                                                                                                                                 
 49   services.xserver.displayManager.gdm.enable = true;                                                                                                                                                                                      
 50   services.xserver.desktopManager.gnome.enable = true;                                                                                                                                                                                    
 51                                                                                                                                                                                                                                           
 52   # Configure keymap in X11                                                                                                                                                                                                               
 53   services.xserver = {                                                                                                                                                                                                                 
 54     layout = "pt";                                                                                                                                                                                                                        
 55     xkbVariant = "";                                                                                                                                                                                                                      
 56   };                                                                                                                                                                                                                                      
 57                                                                                                                                                                                                                                           
 58   # Configure console keymap                                                                                                                                                                                                              
 59   console.keyMap = "pt-latin1";                                                                                                                                                                                                           
 60                                                                                                                                                                                                                                           
 61   # Enable CUPS to print documents.                                                                                                                                                                                                       
 62   services.printing.enable = true;                                                                                                                                                                                                        
 63                                                                                                                                                                                                                                           
 64   # Enable sound with pipewire.                                                                                                                                                                                                           
 65   sound.enable = true;                                                                                                                                                                                                                    
 66   hardware.pulseaudio.enable = false;                                                                                                                                                                                                     
 67   security.rtkit.enable = true;                                                                                                                                                                                                           
 68   services.pipewire = {                                                                                                                                                                                                                   
 69     enable = true;                                                                                                                                                                                                                        
 70     alsa.enable = true;                                                                                                                                                                                                                   
 71     alsa.support32Bit = true;                                                                                                                                                                                                             
 72     pulse.enable = true;                                                                                                                                                                                                                  
 73     # If you want to use JACK applications, uncomment this                                                                                                                                                                                
 74     #jack.enable = true;                                                                                                                                                                                                                  
 75                                                                                                                                                                                                                                           
 76     # use the example session manager (no others are packaged yet so this is enabled by default,                                                                                                                                          
 77     # no need to redefine it in your config for now)                                                                                                                                                                                      
 78     #media-session.enable = true;                                                                                                                                                                                                         
 79   };                                                                                                                                                                                                                                      
 80                                                                                                                                                                                                                                           
 81   # Enable touchpad support (enabled default in most desktopManager).                                                                                                                                                                     
 82   # services.xserver.libinput.enable = true;                                                                                                                                                                                              
 83                                                                                                                                                                                                                                           
 84   # Define a user account. Don't forget to set a password with ‘passwd’.                                                                                                                                                                  
 85   users.users.ruben = {                                                                                                                                                                                                                   
 86     isNormalUser = true;                                                                                                                                                                                                                  
 87     description = "Ruben Roia";                                                                                                                                                                                                           
 88     extraGroups = [ "networkmanager" "wheel" "docker" ];                                                                                                                                                                                  
 89     packages = with pkgs; [                                                                                                                                                                                                               
 90       firefox                                                                                                                                                                                                                             
 91       pkgs.discord                                                                                                                                                                                                                        
 92       home-manager                                                                                                                                                                                                                        
 93       spotify                                                                                                                                                                                                                             
 94       file                                                                                                                                                                                                                                
 95       micro                                                                                                                                                                                                                               
 96       gparted                                                                                                                                                                                                                             
 97     #  thunderbird                                                                                                                                                                                                                        
 98     ];                                                                                                                                                                                                                                    
 99   };                                                                                                                                                                                                                                      
100                                                                                                                                                                                                                                           
101                                                                                                                                                                                                                                           
102   # Allow unfree packages                                                                                                                                                                                                                 
103   nixpkgs.config.allowUnfree = true;                                                                                                                                                                                                      
104                                                                                                                                                                                                                                           
105   # List packages installed in system profile. To search, run:                                                                                                                                                                            
106   # $ nix search wget                                                                                                                                                                                                                     
107   environment.systemPackages = with pkgs; [                                                                                                                                                                                               
108   #  vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.                                                                                                                        
109   #  wget                                                                                                                                                                                                                                 
110      pkgs.gnome.gnome-tweaks                                                                                                                                                                                                              
111      pkgs.gnomeExtensions.appindicator                                                                                                                                                                                                    
112      pkgs.gnomeExtensions.arcmenu                                                                                                                                                                                                         
113      pkgs.gnomeExtensions.clipboard-indicator                                                                                                                                                                                             
114      pkgs.gnomeExtensions.dash-to-panel                                                                                                                                                                                                   
115      pkgs.gnomeExtensions.status-area-horizontal-spacing                                                                                                                                                                                  
116      pkgs.gnomeExtensions.tiling-assistant                                                                                                                                                                                                
117      pkgs.distrobox                                                                                                                                                                                                                       
118      pkgs.steam-run                                                                                                                                                                                                                       
119   ];                                                                                                                                                                                                                                      
120                                                                                                                                                                                                                                           
121   # Some programs need SUID wrappers, can be configured further or are                                                                                                                                                                    
122   # started in user sessions.                                                                                                                                                                                                             
123   # programs.mtr.enable = true;                                                                                                                                                                                                           
124   # programs.gnupg.agent = {                                                                                                                                                                                                              
125   #   enable = true;                                                                                                                                                                                                                      
126   #   enableSSHSupport = true;                                                                                                                                                                                                            
127   # };                                                                                                                                                                                                                                    
128                                                                                                                                                                                                                                           
129 programs.steam = {                                                                                                                                                                                                                        
130   enable = true;                                                                                                                                                                                                                          
131   remotePlay.openFirewall = true; # Open ports in the firewall for Steam Remote Play                                                                                                                                                      
132   dedicatedServer.openFirewall = true; # Open ports in the firewall for Source Dedicated Server                                                                                                                                           
133 };                                                                                                                                                                                                                                        
134                                                                                                                                                                                                                                           
135 virtualisation.docker.enable = true;                                                                                                                                                                                                      
136 virtualisation.docker.rootless = {                                                                                                                                                                                                        
137   enable = true;                                                                                                                                                                                                                          
138   setSocketVariable = true;                                                                                                                                                                                                               
139 };                                                                                                                                                                                                                                        
140                                                                                                                                                                                                                                           
141 virtualisation.virtualbox.host.enable = true;                                                                                                                                                                                             
142    users.extraGroups.vboxusers.members = [ "ruben" ];                                                                                                                                                                                     
143 virtualisation.virtualbox.host.enableExtensionPack = true;                                                                                                                                                                                
144                                                                                                                                                                                                                                           
145 virtualisation.virtualbox.guest.enable = true;                                                                                                                                                                                            
146   virtualisation.virtualbox.guest.x11 = true;                                                                                                                                                                                             
147                                                                                                                                                                                                                                           
148   # List services that you want to enable:                                                                                                                                                                                                
149                                                                                                                                                                                                                                           
150                                                                                                                                                                                                                                           
151 { config, pkgs, ... }:                                                                                                                                                                                                                    
152 let                                                                                                                                                                                                                                       
153   prorealtrading = pkgs.callPackage   ./prorealtrading.nix {};                                                                                                                                                                            
154                                                                                                                                                                                                                                           
155 in                                                                                                                                                                                                                                        
156 {                                                                                                                                                                                                                                         
157                                                                                                                                                                                                                                           
158   environment.systemPackages  = [prorealtrading];                                                                                                                                                                                         
159                                                                                                                                                                                                                                           
160 };                                                                                                                                                                                                                                         
161                                                                                                                                                                                                                                           
162                                                                                                                                                                                                                                           
163   # Enable the OpenSSH daemon.                                                                                                                                                                                                            
164   # services.openssh.enable = true;                                                                                                                                                                                                       
165                                                                                                                                                                                                                                           
166   # Open ports in the firewall.                                                                                                                                                                                                           
167   # networking.firewall.allowedTCPPorts = [ ... ];                                                                                                                                                                                        
168   # networking.firewall.allowedUDPPorts = [ ... ];                                                                                                                                                                                        
169   # Or disable the firewall altogether.                                                                                                                                                                                                   
170   # networking.firewall.enable = false;                                                                                                                                                                                                   
171                                                                                                                                                                                                                                           
172   # This value determines the NixOS release from which the default                                                                                                                                                                        
173   # settings for stateful data, like file locations and database versions                                                                                                                                                                 
174   # on your system were taken. It‘s perfectly fine and recommended to leave                                                                                                                                                               
175   # this value at the release version of the first install of this system.                                                                                                                                                                
176   # Before changing this value read the documentation for this option                                                                                                                                                                     
177   # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).                                                                                                                                                              
178   system.stateVersion = "23.05"; # Did you read the comment?                                                                                                                                                                              
179                                                                                                                                                                                                                                           
180 }                                                                                                                                                                                                                                         
